"use client";

import { useGenerationStore } from "@/lib/generation-store";
import { useUser, SignInButton } from "@clerk/nextjs";
import { useEffect, useState, useRef } from "react";
import ReactMarkdown from "react-markdown"; // Verify if used?
import { WikiLink } from "./wiki-link";

import { Loader2, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

interface WikiContentMonitorProps {
    topic: any;
    initialContent: string;
}

import { useRouter } from "next/navigation";

// ... inside component function ...
export function WikiContentMonitor({ topic, initialContent }: WikiContentMonitorProps) {
    const router = useRouter();
    const { isSignedIn } = useUser();
    const { activeJob, startJob, queue } = useGenerationStore();
    const [localContent, setLocalContent] = useState(initialContent);
    const [isGenerating, setIsGenerating] = useState(false);
    const [wasGenerating, setWasGenerating] = useState(false);

    // Is THIS topic currently being generated?
    const isJobForThisTopic = activeJob?.topicId === topic.id;
    const isThisTopicGenerating = isJobForThisTopic && activeJob?.status === 'generating';

    // Monitor active state to trigger refresh on completion
    useEffect(() => {
        if (isThisTopicGenerating) {
            setWasGenerating(true);
        } else if (wasGenerating && activeJob?.status === 'completed') {
            // Job just finished successfully
            setWasGenerating(false);
            console.log("Generation finished, refreshing page data...");
            router.refresh();
        }
    }, [isThisTopicGenerating, wasGenerating, activeJob?.status, router]);

    // Determine content to show:
    // If we have an active job (generating OR completed) use that content to avoid flicker before refresh
    const displayContent = (isJobForThisTopic && activeJob?.content)
        ? activeJob.content
        : (localContent || initialContent);


    useEffect(() => {
        // Just sync initial if needed? No, purely derived.
    }, []);

    const handleAutoGenerate = () => {
        if (!isGenerating && (!initialContent || initialContent === "Autogenerated stub.")) {
            startJob({
                topicId: topic.id,
                type: 'syllabus',
            });
        }
    };

    // Auto-trigger if empty stub
    const [hasAttemptedAuto, setHasAttemptedAuto] = useState(false);
    const initiatedRef = useRef(false);

    useEffect(() => {
        // If it's a stub, we need to decide whether to auto-trigger or show prompt.

        if (!initialContent || initialContent === "Autogenerated stub.") {
            // Prevent multiple triggers
            if (changeTrackerRef.current) return;

            // GUEST CHECK: If not signed in, we mark as "attempted" (skipped) immediately
            // so the render logic falls through to the "Sign in" prompt.
            if (!isSignedIn) {
                setHasAttemptedAuto(true);
                return;
            }

            // ... proceed with auto-gen logic for logged-in users ...
            initiatedRef.current = true;

            const timer = setTimeout(() => {
                console.log("Auto-triggering generation for stub...");
                startJob({
                    topicId: topic.id,
                    type: 'syllabus',
                });
                setHasAttemptedAuto(true);
            }, 1000);

            return () => clearTimeout(timer);
        }
    }, [isSignedIn, initialContent, startJob, topic.id]); // Add deps for safety 

    const changeTrackerRef = useRef(false); // To satisfy strict mode double invoke prevention if needed, but initiatedRef works.

    // Show streaming or just-completed content (before refresh)
    if (isJobForThisTopic && displayContent) {
        return (
            <div className={cn("space-y-6", isThisTopicGenerating && "animate-pulse-subtle")}>
                <article className="prose prose-stone dark:prose-invert max-w-none prose-lg prose-p:leading-relaxed">
                    <ReactMarkdown components={{ a: WikiLink as any }}>{displayContent}</ReactMarkdown>
                    {isThisTopicGenerating && (
                        <span className="inline-block w-2 h-4 bg-primary animate-pulse ml-1 align-middle" />
                    )}
                </article>
            </div>
        );
    }

    if (!initialContent || initialContent === "Autogenerated stub.") {
        // If we simply haven't triggered yet (timer running), show loading
        // OR if we tried and it failed, show button.

        // Simple heuristic: If we define "attempted" as "timer finished calling startJob",
        // then if !hasAttemptedAuto, we show spinner.
        // If hasAttemptedAuto is true, but we are back here (not active), it means it failed or was cancelled.
        // So show button.

        return (
            <div className="flex flex-col items-center justify-center py-20 px-8 text-center border-2 border-dashed border-border rounded-xl bg-muted/20">
                <Sparkles className="w-12 h-12 text-primary mb-6 opacity-80" />
                <h3 className="text-xl font-serif font-bold mb-3">This Topic is empty</h3>
                <p className="text-muted-foreground max-w-md mb-8">
                    The knowledge base entry exists, but the content hasn't been written yet.
                </p>

                {!hasAttemptedAuto ? (
                    <div className="flex items-center gap-3 text-muted-foreground animate-pulse">
                        <Loader2 className="w-5 h-5 animate-spin" />
                        <span>Initializing AI Agent...</span>
                    </div>
                ) : (
                    <div className="flex flex-col items-center gap-3">
                        {!isSignedIn ? (
                            <SignInButton mode="modal">
                                <button className="group relative flex items-center gap-3 bg-red-500/5 hover:bg-red-500/10 text-red-500 px-6 py-4 rounded-xl border border-red-500/20 transition-all hover:scale-105 cursor-pointer shadow-lg shadow-red-500/5">
                                    <div className="p-2 bg-red-500/10 rounded-full group-hover:bg-red-500/20 transition-colors">
                                        <Sparkles className="w-4 h-4" />
                                    </div>
                                    <div className="flex flex-col items-start">
                                        <span className="font-semibold text-sm">Sign in to Generate</span>
                                        <span className="text-xs opacity-70">Guests can only read existing content</span>
                                    </div>
                                </button>
                            </SignInButton>
                        ) : (
                            <button
                                onClick={() => startJob({ topicId: topic.id, type: 'syllabus' })}
                                className="px-6 py-3 bg-primary text-primary-foreground rounded-full font-medium hover:scale-105 transition-transform shadow-lg shadow-primary/20 flex items-center gap-2"
                            >
                                <Sparkles className="w-4 h-4" /> Generate Article
                            </button>
                        )}
                    </div>
                )}
            </div>
        );
    }

    return (
        <div className="mb-12">
            <h2 className="text-2xl font-serif mb-6 text-primary/80 italic">Overview</h2>
            <article className="prose prose-stone dark:prose-invert max-w-none prose-lg prose-p:leading-relaxed">
                <ReactMarkdown>{localContent}</ReactMarkdown>
            </article>
        </div>
    );
}
